# PluSO Model Catalog

anthropic_models:
  claude-3-opus:
    description: "Most capable model, best for complex tasks requiring deep analysis"
    capabilities:
      - Complex reasoning
      - In-depth analysis
      - Code generation
      - Multi-turn dialogue
    use_cases:
      - Legal document analysis
      - Scientific research
      - Complex coding tasks
    specs:
      context_window: 200000
      cost_per_1k: "$0.015"
      avg_speed: "2-3s"
    recommended_for:
      - High-stakes decisions
      - Complex analysis
      - Research tasks

  claude-3-sonnet:
    description: "Balanced model for general use, good performance/cost ratio"
    capabilities:
      - General conversation
      - Basic analysis
      - Code assistance
    use_cases:
      - Customer support
      - Content generation
      - Data analysis
    specs:
      context_window: 150000
      cost_per_1k: "$0.008"
      avg_speed: "1-2s"
    recommended_for:
      - General purpose tasks
      - Medium complexity work
      - Customer interactions

  claude-3-haiku:
    description: "Fast, efficient model for simple tasks"
    capabilities:
      - Quick responses
      - Basic tasks
      - Simple analysis
    use_cases:
      - Chat interfaces
      - Quick queries
      - Basic assistance
    specs:
      context_window: 100000
      cost_per_1k: "$0.003"
      avg_speed: "0.5-1s"
    recommended_for:
      - High-volume tasks
      - Simple queries
      - Real-time applications

openai_models:
  gpt-4-turbo:
    description: "Advanced model with strong general capabilities"
    capabilities:
      - Complex reasoning
      - Code generation
      - Creative writing
    use_cases:
      - Software development
      - Content creation
      - Problem-solving
    specs:
      context_window: 128000
      cost_per_1k: "$0.01"
      avg_speed: "2-3s"
    recommended_for:
      - Complex tasks
      - Code generation
      - Creative work

  gpt-3.5-turbo:
    description: "Fast, cost-effective model for general use"
    capabilities:
      - Basic conversation
      - Simple analysis
      - Quick responses
    use_cases:
      - Chat applications
      - Basic support
      - Simple queries
    specs:
      context_window: 16000
      cost_per_1k: "$0.0015"
      avg_speed: "0.5-1s"
    recommended_for:
      - High-volume tasks
      - Cost-sensitive applications
      - Simple interactions

selection_criteria:
  response_time:
    critical: "claude-3-haiku, gpt-3.5-turbo"
    balanced: "claude-3-sonnet"
    not_critical: "claude-3-opus, gpt-4-turbo"
    
  cost_efficiency:
    high: "claude-3-haiku, gpt-3.5-turbo"
    medium: "claude-3-sonnet"
    low: "claude-3-opus, gpt-4-turbo"
    
  complexity:
    simple: "claude-3-haiku, gpt-3.5-turbo"
    medium: "claude-3-sonnet"
    complex: "claude-3-opus, gpt-4-turbo"
    
  context_needed:
    small: "claude-3-haiku, gpt-3.5-turbo"
    medium: "claude-3-sonnet, gpt-4-turbo"
    large: "claude-3-opus"
