# Agent Configuration Template
name: "{{name}}"
description: "{{description}}"
type: "{{type}}"
industry: "{{industry}}"
template: "{{template}}"

# Model Configuration
models:
  primary:
    name: "{{primary_model}}"
    temperature: 0.7
    max_tokens: 4000
  fallback:
    name: "{{fallback_model}}"
    temperature: 0.7
    max_tokens: 2048
  embedding:
    name: "{{embedding_model}}"
  vision:
    name: "{{vision_model}}"

# System Configuration
system:
  memory_limit: "512MB"
  timeout: 30000  # ms
  rate_limit: 100  # requests per minute

# Features
features: {{features}}

# System Prompt
system_prompt: |
  {{system_prompt}}

# Capabilities
capabilities:
  - "chat"        # Basic chat functionality
  - "tools"       # Can use external tools
  - "memory"      # Has persistent memory
  - "web"         # Can access web content

# Metrics Configuration
metrics:
  enabled: true
  flush_interval: 60000  # ms
  custom_metrics:
    - name: "response_time"
      type: "histogram"
      description: "Time taken to respond to user queries"
    - name: "token_usage"
      type: "counter"
      description: "Number of tokens used in responses"
    - name: "success_rate"
      type: "gauge"
      description: "Rate of successful responses"

# Security
security:
  auth_required: true
  rate_limiting: true
  input_validation: true
  output_sanitization: true

# Export Options
export:
  sdk:
    - typescript
    - python
  api:
    - rest
    - graphql
  wasm: true
