-- Create industries table
CREATE TABLE IF NOT EXISTS public.industries (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    icon TEXT,
    templates TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create templates table
CREATE TABLE IF NOT EXISTS public.templates (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    type TEXT NOT NULL,
    industry TEXT REFERENCES public.industries(id),
    system_prompt TEXT,
    features JSONB,
    required_models JSONB,
    evaluation_criteria JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert industries
INSERT INTO public.industries (id, name, description, icon, templates) VALUES
    ('customer-service', 'Customer Service', 'AI agents for customer support, inquiries, and issue resolution', '💬', ARRAY['customer-service']),
    ('legal', 'Legal', 'AI agents for legal research, document analysis, and compliance', '⚖️', ARRAY['legal-research']),
    ('healthcare', 'Healthcare', 'AI agents for medical information, patient support, and health monitoring', '🏥', ARRAY['healthcare']),
    ('education', 'Education', 'AI agents for tutoring, course assistance, and learning support', '📚', ARRAY['education']),
    ('finance', 'Finance', 'AI agents for financial analysis, advisory, and market research', '💰', ARRAY['finance']),
    ('hr', 'Human Resources', 'AI agents for recruitment, employee support, and HR operations', '👥', ARRAY['hr']),
    ('clubs', 'Clubs & Entertainment', 'AI agents for event management, member services, and entertainment venues', '🎭', ARRAY['clubs']),
    ('hospitality', 'Hospitality', 'AI agents for hotel management, guest services, and hospitality operations', '🏨', ARRAY['hospitality']),
    ('real-estate', 'Real Estate', 'AI agents for property listings, client matching, and real estate transactions', '🏠', ARRAY['real-estate', 'real-estate-content', 'real-estate-analysis', 'real-estate-negotiation']),
    ('marketing', 'Marketing', 'AI agents for content creation, marketing campaigns, and brand management', '📣', ARRAY['marketing'])
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    icon = EXCLUDED.icon,
    templates = EXCLUDED.templates,
    updated_at = CURRENT_TIMESTAMP;

-- Insert templates
INSERT INTO public.templates (id, name, description, type, industry, system_prompt, features, required_models, evaluation_criteria) VALUES
    ('customer-service', 'Customer Support Agent', 'A helpful agent for handling customer inquiries and support requests', 'chat', 'customer-service',
     'You are a helpful customer service agent. Your role is to assist customers with their inquiries, resolve issues, and provide accurate information about our products and services.',
     '{"features": ["knowledge_base", "ticket_creation", "conversation_history", "sentiment_analysis"]}',
     '{"primary": ["gpt-4", "claude-2"], "fallback": ["gpt-3.5-turbo"], "embedding": ["text-embedding-ada-002"]}',
     '[{"id": "response_accuracy", "name": "Response Accuracy", "description": "Measures the accuracy and relevance of agent responses", "threshold": 0.9, "weight": 0.4}]'),
    
    ('real-estate-search', 'Property Search Assistant', 'An agent specialized in helping clients find properties matching their criteria', 'rag', 'real-estate',
     'You are a real estate search assistant. Your role is to help clients find properties that match their criteria, provide detailed property information, and schedule viewings.',
     '{"features": ["property_search", "map_integration", "viewing_scheduler", "preference_tracking", "image_analysis"]}',
     '{"primary": ["gpt-4-vision", "claude-3"], "fallback": ["gpt-4"], "embedding": ["text-embedding-ada-002"]}',
     '[{"id": "search_relevance", "name": "Search Relevance", "description": "Accuracy of property matches to client criteria", "threshold": 0.9, "weight": 0.4}]'),
    
    ('real-estate-content', 'Real Estate Content Creator', 'An agent specialized in creating compelling property listings and marketing content', 'creative', 'real-estate',
     'You are a real estate content creator. Your role is to create engaging property descriptions, marketing materials, and social media content that highlights key features and attracts potential buyers.',
     '{"features": ["property_description", "social_media_content", "email_campaigns", "image_captioning", "seo_optimization"]}',
     '{"primary": ["gpt-4", "claude-2"], "embedding": ["text-embedding-ada-002"]}',
     '[{"id": "content_quality", "name": "Content Quality", "description": "Engagement and effectiveness of content", "threshold": 0.85, "weight": 0.4}]'),
    
    ('real-estate-analysis', 'Market Analysis Assistant', 'An agent specialized in real estate market analysis and property valuation', 'analysis', 'real-estate',
     'You are a real estate market analyst. Your role is to analyze market trends, provide property valuations, and generate comprehensive market reports.',
     '{"features": ["market_analysis", "price_prediction", "trend_analysis", "comparative_analysis", "investment_roi"]}',
     '{"primary": ["gpt-4", "claude-2"], "embedding": ["text-embedding-ada-002"]}',
     '[{"id": "analysis_accuracy", "name": "Analysis Accuracy", "description": "Accuracy of market analysis and predictions", "threshold": 0.9, "weight": 0.5}]'),
    
    ('real-estate-negotiation', 'Deal Negotiation Assistant', 'An agent specialized in real estate deal negotiation and transaction management', 'chat', 'real-estate',
     'You are a real estate negotiation assistant. Your role is to help agents with deal negotiations, offer management, and transaction coordination.',
     '{"features": ["offer_analysis", "negotiation_strategy", "contract_review", "transaction_tracking", "communication_management"]}',
     '{"primary": ["gpt-4", "claude-2"], "embedding": ["text-embedding-ada-002"]}',
     '[{"id": "negotiation_success", "name": "Negotiation Success", "description": "Effectiveness of negotiation strategies", "threshold": 0.85, "weight": 0.4}]'),
    
    ('hospitality-concierge', 'Hotel Concierge Assistant', 'A virtual concierge for hotel guests handling bookings, inquiries, and requests', 'chat', 'hospitality',
     'You are a hotel concierge assistant. Your role is to help guests with room bookings, restaurant reservations, local recommendations, and special requests.',
     '{"features": ["booking_system", "restaurant_reservations", "local_recommendations", "request_tracking", "availability_checker"]}',
     '{"primary": ["gpt-4", "claude-2"], "fallback": ["gpt-3.5-turbo"], "embedding": ["text-embedding-ada-002"]}',
     '[{"id": "booking_accuracy", "name": "Booking Accuracy", "description": "Accuracy of reservation handling", "threshold": 0.95, "weight": 0.4}]'),
    
    ('content-creator', 'Content Creation Assistant', 'An AI assistant for generating and optimizing various types of content', 'creative', 'marketing',
     'You are a content creation assistant. Your role is to help create engaging content across various formats, optimize for different platforms, and maintain brand consistency.',
     '{"features": ["text_generation", "image_generation", "seo_optimization", "social_media_formatting", "content_scheduling"]}',
     '{"primary": ["gpt-4", "claude-2"], "image": ["dall-e-3"], "embedding": ["text-embedding-ada-002"]}',
     '[{"id": "content_quality", "name": "Content Quality", "description": "Overall quality and engagement of content", "threshold": 0.9, "weight": 0.4}]'),
    
    ('legal-research', 'Legal Research Assistant', 'An agent specialized in legal research and document analysis', 'rag', 'legal',
     'You are a legal research assistant. Your role is to help legal professionals with research tasks, document analysis, and case law references.',
     '{"features": ["document_analysis", "case_law_search", "citation_management", "redaction"]}',
     '{"primary": ["gpt-4", "claude-2"], "embedding": ["text-embedding-ada-002"]}',
     '[{"id": "legal_accuracy", "name": "Legal Accuracy", "description": "Accuracy of legal information and citations", "threshold": 0.95, "weight": 0.5}]')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    type = EXCLUDED.type,
    industry = EXCLUDED.industry,
    system_prompt = EXCLUDED.system_prompt,
    features = EXCLUDED.features,
    required_models = EXCLUDED.required_models,
    evaluation_criteria = EXCLUDED.evaluation_criteria,
    updated_at = CURRENT_TIMESTAMP;

-- Insert templates for Customer Service
INSERT INTO public.templates (id, name, description, type, industry, system_prompt, features, required_models, evaluation_criteria) VALUES
    ('cs-general-support', 'General Support Agent', 'Handles general customer inquiries and basic support requests', 'chat', 'customer-service',
     'You are a general customer service agent handling basic inquiries and support requests.',
     '{"features": ["ticket_management", "faq_knowledge", "response_templates", "customer_history"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "response_quality", "threshold": 0.9}]'),
    ('cs-technical-support', 'Technical Support Specialist', 'Provides technical troubleshooting and product support', 'chat', 'customer-service',
     'You are a technical support specialist helping customers resolve complex technical issues.',
     '{"features": ["technical_diagnostics", "step_by_step_guidance", "product_knowledge"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "technical_accuracy", "threshold": 0.95}]'),
    ('cs-billing-support', 'Billing Support Agent', 'Handles billing inquiries and payment-related issues', 'chat', 'customer-service',
     'You are a billing support specialist helping with payment and subscription issues.',
     '{"features": ["payment_processing", "subscription_management", "refund_handling"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "billing_accuracy", "threshold": 0.98}]'),
    ('cs-onboarding', 'Customer Onboarding Specialist', 'Guides new customers through product setup and orientation', 'chat', 'customer-service',
     'You are an onboarding specialist helping new customers get started with our products.',
     '{"features": ["guided_setup", "product_training", "welcome_workflow"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "onboarding_success", "threshold": 0.9}]'),
    ('cs-retention', 'Customer Retention Specialist', 'Focuses on customer satisfaction and preventing churn', 'chat', 'customer-service',
     'You are a retention specialist working to maintain customer satisfaction and prevent churn.',
     '{"features": ["satisfaction_tracking", "retention_strategies", "loyalty_programs"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "retention_rate", "threshold": 0.85}]');

-- Insert templates for Legal
INSERT INTO public.templates (id, name, description, type, industry, system_prompt, features, required_models, evaluation_criteria) VALUES
    ('legal-research', 'Legal Research Assistant', 'Conducts legal research and case law analysis', 'research', 'legal',
     'You are a legal research assistant helping with case law and precedent research.',
     '{"features": ["case_law_search", "precedent_analysis", "legal_database_access"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "research_accuracy", "threshold": 0.95}]'),
    ('legal-document', 'Document Review Specialist', 'Reviews and analyzes legal documents', 'analysis', 'legal',
     'You are a legal document specialist reviewing contracts and legal documents.',
     '{"features": ["document_analysis", "contract_review", "compliance_check"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "review_accuracy", "threshold": 0.98}]'),
    ('legal-compliance', 'Compliance Advisor', 'Provides guidance on regulatory compliance', 'advisory', 'legal',
     'You are a compliance advisor helping with regulatory requirements and compliance.',
     '{"features": ["regulation_tracking", "compliance_assessment", "risk_analysis"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "compliance_accuracy", "threshold": 0.98}]'),
    ('legal-ip', 'IP Law Specialist', 'Handles intellectual property matters', 'specialized', 'legal',
     'You are an IP law specialist dealing with patents, trademarks, and copyright issues.',
     '{"features": ["ip_search", "trademark_analysis", "patent_review"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "ip_expertise", "threshold": 0.95}]'),
    ('legal-contracts', 'Contract Generator', 'Creates and customizes legal contracts', 'generation', 'legal',
     'You are a contract generation specialist creating customized legal documents.',
     '{"features": ["template_customization", "clause_library", "version_control"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "contract_quality", "threshold": 0.95}]');

-- Insert templates for Healthcare
INSERT INTO public.templates (id, name, description, type, industry, system_prompt, features, required_models, evaluation_criteria) VALUES
    ('health-info', 'Medical Information Assistant', 'Provides general medical information and guidance', 'information', 'healthcare',
     'You are a medical information assistant providing general health information.',
     '{"features": ["symptom_checker", "medical_database", "health_education"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "info_accuracy", "threshold": 0.98}]'),
    ('health-appointment', 'Appointment Scheduler', 'Manages medical appointments and scheduling', 'scheduling', 'healthcare',
     'You are an appointment scheduling assistant for healthcare services.',
     '{"features": ["calendar_management", "reminder_system", "priority_scheduling"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "scheduling_efficiency", "threshold": 0.9}]'),
    ('health-records', 'Medical Records Assistant', 'Helps manage and organize medical records', 'records', 'healthcare',
     'You are a medical records assistant helping organize health information.',
     '{"features": ["record_organization", "data_entry", "history_tracking"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "record_accuracy", "threshold": 0.99}]'),
    ('health-insurance', 'Insurance Claims Assistant', 'Assists with healthcare insurance claims', 'insurance', 'healthcare',
     'You are an insurance claims assistant helping with healthcare coverage.',
     '{"features": ["claims_processing", "coverage_verification", "benefits_explanation"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "claims_accuracy", "threshold": 0.98}]'),
    ('health-wellness', 'Wellness Coach', 'Provides health and wellness guidance', 'coaching', 'healthcare',
     'You are a wellness coach providing health and lifestyle guidance.',
     '{"features": ["wellness_planning", "progress_tracking", "lifestyle_advice"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "coaching_quality", "threshold": 0.9}]');

-- Insert templates for Education
INSERT INTO public.templates (id, name, description, type, industry, system_prompt, features, required_models, evaluation_criteria) VALUES
    ('edu-tutor', 'Personal Tutor', 'Provides one-on-one tutoring in various subjects', 'tutoring', 'education',
     'You are a personal tutor helping students understand various subjects.',
     '{"features": ["subject_expertise", "practice_exercises", "progress_tracking"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "teaching_effectiveness", "threshold": 0.9}]'),
    ('edu-homework', 'Homework Helper', 'Assists with homework and assignments', 'assistance', 'education',
     'You are a homework assistant helping students with assignments.',
     '{"features": ["problem_solving", "step_by_step_guidance", "concept_explanation"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "help_quality", "threshold": 0.95}]'),
    ('edu-study', 'Study Guide Creator', 'Creates personalized study materials', 'content', 'education',
     'You are a study guide creator developing learning materials.',
     '{"features": ["material_creation", "quiz_generation", "summary_writing"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "material_quality", "threshold": 0.95}]'),
    ('edu-language', 'Language Learning Assistant', 'Helps with language learning and practice', 'language', 'education',
     'You are a language learning assistant helping with language acquisition.',
     '{"features": ["conversation_practice", "grammar_check", "vocabulary_building"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "language_teaching", "threshold": 0.9}]'),
    ('edu-research', 'Research Assistant', 'Helps with academic research and writing', 'research', 'education',
     'You are a research assistant helping with academic projects.',
     '{"features": ["research_guidance", "citation_help", "paper_structure"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "research_quality", "threshold": 0.95}]');

-- Insert templates for Finance
INSERT INTO public.templates (id, name, description, type, industry, system_prompt, features, required_models, evaluation_criteria) VALUES
    ('finance-advisor', 'Financial Advisor', 'Provides personal financial advice and planning', 'advisory', 'finance',
     'You are a financial advisor helping with personal finance decisions.',
     '{"features": ["investment_planning", "budget_analysis", "retirement_planning"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "advice_quality", "threshold": 0.95}]'),
    ('finance-analyst', 'Market Analyst', 'Analyzes market trends and investment opportunities', 'analysis', 'finance',
     'You are a market analyst providing investment and market insights.',
     '{"features": ["market_analysis", "trend_tracking", "risk_assessment"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "analysis_accuracy", "threshold": 0.95}]'),
    ('finance-tax', 'Tax Planning Assistant', 'Helps with tax planning and preparation', 'tax', 'finance',
     'You are a tax planning assistant helping with tax-related matters.',
     '{"features": ["tax_planning", "deduction_finder", "compliance_check"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "tax_accuracy", "threshold": 0.98}]'),
    ('finance-budget', 'Budget Planner', 'Assists with personal and business budgeting', 'planning', 'finance',
     'You are a budget planning assistant helping create and manage budgets.',
     '{"features": ["budget_creation", "expense_tracking", "savings_planning"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "planning_quality", "threshold": 0.9}]'),
    ('finance-crypto', 'Cryptocurrency Advisor', 'Provides guidance on cryptocurrency investments', 'crypto', 'finance',
     'You are a cryptocurrency advisor helping with digital asset investments.',
     '{"features": ["crypto_analysis", "portfolio_tracking", "risk_management"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "crypto_expertise", "threshold": 0.9}]');

-- Insert templates for Real Estate
INSERT INTO public.templates (id, name, description, type, industry, system_prompt, features, required_models, evaluation_criteria) VALUES
    ('re-search', 'Property Search Assistant', 'Helps find properties matching client criteria', 'search', 'real-estate',
     'You are a property search assistant helping clients find their ideal properties.',
     '{"features": ["property_matching", "virtual_tours", "neighborhood_analysis"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "search_accuracy", "threshold": 0.9}]'),
    ('re-market', 'Market Analysis Expert', 'Provides real estate market analysis', 'analysis', 'real-estate',
     'You are a real estate market analyst providing market insights.',
     '{"features": ["market_analysis", "price_trends", "investment_potential"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "analysis_quality", "threshold": 0.95}]'),
    ('re-listing', 'Listing Specialist', 'Creates and manages property listings', 'listing', 'real-estate',
     'You are a listing specialist creating compelling property descriptions.',
     '{"features": ["listing_creation", "photo_management", "marketing_copy"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "listing_quality", "threshold": 0.9}]'),
    ('re-investment', 'Investment Advisor', 'Analyzes real estate investment opportunities', 'investment', 'real-estate',
     'You are a real estate investment advisor helping with property investments.',
     '{"features": ["roi_analysis", "risk_assessment", "portfolio_planning"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "investment_advice", "threshold": 0.95}]'),
    ('re-transaction', 'Transaction Coordinator', 'Manages real estate transactions', 'transaction', 'real-estate',
     'You are a transaction coordinator managing real estate deals.',
     '{"features": ["document_management", "timeline_tracking", "closing_coordination"]}',
     '{"primary": ["gpt-4"], "fallback": ["gpt-3.5-turbo"]}',
     '[{"id": "transaction_efficiency", "threshold": 0.95}]');
