// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from './routes/_app.tsx';
import * as $_error from './routes/_error.tsx';
import * as $_layout from './routes/_layout.tsx';
import * as $_middleware from './routes/_middleware.ts';
import * as $about from './routes/about.tsx';
import * as $admin_index from './routes/admin/index.tsx';
import * as $api_chat_maia from './routes/api/chat/maia.ts';
import * as $api_dashboard from './routes/api/dashboard.ts';
import * as $api_index from './routes/api/index.ts';
import * as $api_profile from './routes/api/profile.ts';
import * as $api_settings from './routes/api/settings.ts';
import * as $api_health from './routes/api/health.ts';
import * as $api_health_islands from './routes/api/health/islands.ts';
import * as $api_health_metrics from './routes/api/health/metrics.ts';
import * as $api_metrics_index from './routes/api/metrics/index.ts';
import * as $api_metrics_verify from './routes/api/metrics/verify.ts';
import * as $api_metrics_record from './routes/api/metrics/record.ts';
import * as $api_models from './routes/api/models.ts';
import * as $api_ping from './routes/api/ping.ts';
import * as $contact from './routes/contact.tsx';
import * as $dashboard from './routes/dashboard.tsx';
import * as $dashboard_layout from './routes/dashboard/_layout.tsx';
import * as $dashboard_agents_id_ from './routes/dashboard/agents/[id].tsx';
import * as $dashboard_agents_deploy_agentId_ from './routes/dashboard/agents/deploy/[agentId].tsx';
import * as $dashboard_agents_examples from './routes/dashboard/agents/examples.tsx';
import * as $dashboard_agents_index from './routes/dashboard/agents/index.tsx';
import * as $dashboard_analytics_index from './routes/dashboard/analytics/index.tsx';
import * as $dashboard_create from './routes/dashboard/create.tsx';
import * as $dashboard_index from './routes/dashboard/index.tsx';
import * as $dashboard_metrics_index from './routes/dashboard/metrics/index.tsx';
import * as $dashboard_models_index from './routes/dashboard/models/index.tsx';
import * as $dashboard_monitoring_index from './routes/dashboard/monitoring/index.tsx';
import * as $dashboard_playground from './routes/dashboard/playground.tsx';
import * as $dashboard_profile from './routes/dashboard/profile.tsx';
import * as $dashboard_settings from './routes/dashboard/settings.tsx';
import * as $index from './routes/index.tsx';
import * as $profile from './routes/profile.tsx';
import * as $settings from './routes/settings.tsx';
import * as $settings_index from './routes/settings/index.tsx';
import * as $tools from './routes/tools.tsx';
import * as $tools_form_filler from './routes/tools/form-filler.tsx';
import * as $tools_monitor from './routes/tools/monitor.tsx';
import * as $tools_pdf from './routes/tools/pdf.tsx';
import * as $tools_scraper from './routes/tools/scraper.tsx';
import * as $tools_screenshot from './routes/tools/screenshot.tsx';
import * as $tools_seo from './routes/tools/seo.tsx';
import * as $MaiaWidget from './islands/agents/maia/MaiaWidget.tsx';
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    './routes/_app.tsx': $_app,
    './routes/_error.tsx': $_error,
    './routes/_layout.tsx': $_layout,
    './routes/_middleware.ts': $_middleware,
    './routes/about.tsx': $about,
    './routes/admin/index.tsx': $admin_index,
    './routes/api/chat/maia.ts': $api_chat_maia,
    './routes/api/dashboard.ts': $api_dashboard,
    './routes/api/index.ts': $api_index,
    './routes/api/profile.ts': $api_profile,
    './routes/api/settings.ts': $api_settings,
    './routes/api/health.ts': $api_health,
    './routes/api/health/islands.ts': $api_health_islands,
    './routes/api/health/metrics.ts': $api_health_metrics,
    './routes/api/metrics/index.ts': $api_metrics_index,
    './routes/api/metrics/verify.ts': $api_metrics_verify,
    './routes/api/metrics/record.ts': $api_metrics_record,
    './routes/api/models.ts': $api_models,
    './routes/api/ping.ts': $api_ping,
    './routes/contact.tsx': $contact,
    './routes/dashboard.tsx': $dashboard,
    './routes/dashboard/_layout.tsx': $dashboard_layout,
    './routes/dashboard/agents/[id].tsx': $dashboard_agents_id_,
    './routes/dashboard/agents/deploy/[agentId].tsx': $dashboard_agents_deploy_agentId_,
    './routes/dashboard/agents/examples.tsx': $dashboard_agents_examples,
    './routes/dashboard/agents/index.tsx': $dashboard_agents_index,
    './routes/dashboard/analytics/index.tsx': $dashboard_analytics_index,
    './routes/dashboard/create.tsx': $dashboard_create,
    './routes/dashboard/index.tsx': $dashboard_index,
    './routes/dashboard/metrics/index.tsx': $dashboard_metrics_index,
    './routes/dashboard/models/index.tsx': $dashboard_models_index,
    './routes/dashboard/monitoring/index.tsx': $dashboard_monitoring_index,
    './routes/dashboard/playground.tsx': $dashboard_playground,
    './routes/dashboard/profile.tsx': $dashboard_profile,
    './routes/dashboard/settings.tsx': $dashboard_settings,
    './routes/index.tsx': $index,
    './routes/profile.tsx': $profile,
    './routes/settings.tsx': $settings,
    './routes/settings/index.tsx': $settings_index,
    './routes/tools.tsx': $tools,
    './routes/tools/form-filler.tsx': $tools_form_filler,
    './routes/tools/monitor.tsx': $tools_monitor,
    './routes/tools/pdf.tsx': $tools_pdf,
    './routes/tools/scraper.tsx': $tools_scraper,
    './routes/tools/screenshot.tsx': $tools_screenshot,
    './routes/tools/seo.tsx': $tools_seo,
  },
  islands: {
    './islands/agents/maia/MaiaWidget.tsx': $MaiaWidget,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
